"""create printers table

Revision ID: 0001
Revises: 
Create Date: 2026-07-02 01:48:48.765673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), server_default='default', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('ipp_path', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('capabilities_raw', sa.JSON(), nullable=True),
    sa.Column('capabilities_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_tenant_id'), 'printers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printers_tenant_id'), table_name='printers')
    op.drop_table('printers')
    # ### end Alembic commands ###
