"""add port and use_tls columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-02 01:51:42.578645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('port', sa.Integer(), server_default='631', nullable=False))
    op.add_column('printers', sa.Column('use_tls', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printers', 'use_tls')
    op.drop_column('printers', 'port')
    # ### end Alembic commands ###
