"""create mosyle settings and devices tables

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-02 19:01:38.666997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mosyle_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mosyle_devices_mac_address'), 'mosyle_devices', ['mac_address'], unique=True)
    op.create_table('mosyle_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(), nullable=True),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('admin_password_encrypted', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('device_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mosyle_settings')
    op.drop_index(op.f('ix_mosyle_devices_mac_address'), table_name='mosyle_devices')
    op.drop_table('mosyle_devices')
    # ### end Alembic commands ###
