"""add google workspace users, device overrides, job mac address

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-03 03:58:49.847242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_user_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('resolved_email', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_user_overrides_mac_address'), 'device_user_overrides', ['mac_address'], unique=True)
    op.create_table('google_workspace_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_workspace_users_email'), 'google_workspace_users', ['email'], unique=True)
    op.add_column('jobs', sa.Column('mac_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_mac_address'), 'jobs', ['mac_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_mac_address'), table_name='jobs')
    op.drop_column('jobs', 'mac_address')
    op.drop_index(op.f('ix_google_workspace_users_email'), table_name='google_workspace_users')
    op.drop_table('google_workspace_users')
    op.drop_index(op.f('ix_device_user_overrides_mac_address'), table_name='device_user_overrides')
    op.drop_table('device_user_overrides')
    # ### end Alembic commands ###
